# Generated by Django 4.2.7 on 2023-11-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tabela_Disponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ubs', models.CharField(choices=[('Anita Ferraz', 'Anita Ferraz'), ('Cacimba Velha', 'Cacimba Velha'), ('Campestre Norte', 'Campestre Norte'), ('Cidade Jardim', 'Cidade Jardim'), ('Coroatá', 'Coroatá'), ('Ininga', 'Ininga'), ('Parque Universitário', 'Parque Universitário'), ('Piçarreira', 'Piçarreira'), ('Planalto Uruguai', 'Planalto Uruguai'), ('Santa Bárbara', 'Santa Bárbara'), ('Santa Isabel', 'Santa Isabel'), ('Santa Luz', 'Santa luz'), ('Santa Teresa', 'Santa teresa'), ('São João', 'São João'), ('Satélite', 'Satélite'), ('Soinho', 'Soinho'), ('Taquari', 'Taquari'), ('Vale do Gavião', 'Vale do Gavião'), ('Vila Bandeirantes', 'Vila Bandeirantes'), ('Vila União', 'Vila união')], max_length=30)),
                ('nome_vacina', models.CharField(choices=[('Dupla Adulto (Difteria e Tétano)', 'Dupla Adulto (Difteria e Tétano)'), ('Febre Amarela', 'Febre Amarela'), ('Hepatite A', 'Hepatite A'), ('Hepatite B', 'Hepatite B'), ('Inativada Poliomielite', 'Inativada Poliomielite'), ('Meningocócica ACWY', 'Meningocócica ACWY'), ('Meninocócica C', 'Meninocócica C'), ('Oral Poliomielite', 'Oral Poliomielite'), ('Oral Rotavírus humano', 'Oral Rotavírus Humano'), ('Papiloma Vírus Humano Quadrivalente', 'Papiloma Vírus Humano Quadrivalente'), ('Pentavalente (DTP/HB/Hib)', 'Pentavalente (DTP/HB/Hib)'), ('Pneumocócica 10 Valente', 'Pneumocócica 10 Valente'), ('DTP - Tríplice Bacteriana(Difteria, Tétano, Coqueluche)', 'DTP - Tríplice Bacteriana(Difteria, Tétano, Coqueluche)'), ('SCR - Tríplice Viral(Sarampo, Caxumba e Rubéola)', 'SCR - Tríplice Viral(Sarampo, Caxumba e Rubéola)'), ('Varicela', 'Varicela')], max_length=70)),
                ('disponibilidade', models.CharField(choices=[('Disponível', 'Disponível'), ('Indisponível', 'Indisponível')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome_ubs', 'nome_vacina'],
            },
        ),
        migrations.CreateModel(
            name='Tabela_Funcionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ubs', models.CharField(choices=[('Anita Ferraz', 'Anita Ferraz'), ('Cacimba Velha', 'Cacimba Velha'), ('Campestre Norte', 'Campestre Norte'), ('Cidade Jardim', 'Cidade Jardim'), ('Coroatá', 'Coroatá'), ('Ininga', 'Ininga'), ('Parque Universitário', 'Parque Universitário'), ('Piçarreira', 'Piçarreira'), ('Planalto Uruguai', 'Planalto Uruguai'), ('Santa Bárbara', 'Santa Bárbara'), ('Santa Isabel', 'Santa Isabel'), ('Santa Luz', 'Santa luz'), ('Santa Teresa', 'Santa teresa'), ('São João', 'São João'), ('Satélite', 'Satélite'), ('Soinho', 'Soinho'), ('Taquari', 'Taquari'), ('Vale do Gavião', 'Vale do Gavião'), ('Vila Bandeirantes', 'Vila Bandeirantes'), ('Vila União', 'Vila união')], max_length=30)),
                ('horario', models.CharField(max_length=70)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome_ubs'],
            },
        ),
    ]
